name = "cf-worker-mailer"
main = "src/index.ts"
compatibility_date = "2026-01-28"

send_email = [
  { name = "CF_MAILER", destination_address = "patrronai@gmail.com" }
]

[vars]
SENDER_NAME = "Auteric Landing"
SENDER_EMAIL = "hello@auteric.com"
PATH_NAME = "/send"

[observability]
enabled = true
